#!/bin/bash

echo "Setting up default identify..."
ssh-keygen -q

echo "New keys have been generated..."
ls ~/.ssh/id_rsa*

echo "Adding key to the ssh-agent..."
eval `ssh-agent`
ssh-add ~/.ssh/id_rsa

echo "Done!"

echo ""
cat ~/.ssh/id_rsa.pub

